"""add model menu

Revision ID: 02bb9d079758
Revises: 25eea067d956
Create Date: 2023-01-13 14:55:50.659160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bb9d079758'
down_revision = '25eea067d956'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_menu_id'), 'menu_menu', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_menu_id'), table_name='menu_menu')
    op.drop_table('menu_menu')
    # ### end Alembic commands ###
