"""First

Revision ID: 25eea067d956
Revises: 
Create Date: 2023-01-13 14:41:50.285804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25eea067d956'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
